// Code generated by protoc-gen-go.
// source: proto/location.proto
// DO NOT EDIT!

/*
Package location is a generated protocol buffer package.

It is generated from these files:
	proto/location.proto

It has these top-level messages:
	Location
*/
package location

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Location struct {
	Latitude         *string `protobuf:"bytes,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude        *string `protobuf:"bytes,2,opt,name=longitude" json:"longitude,omitempty"`
	AltitudeMsl      *string `protobuf:"bytes,3,opt,name=altitude_msl" json:"altitude_msl,omitempty"`
	GroundSpeed      *string `protobuf:"bytes,4,opt,name=ground_speed" json:"ground_speed,omitempty"`
	Heading          *string `protobuf:"bytes,5,opt,name=heading" json:"heading,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Location) GetLatitude() string {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return ""
}

func (m *Location) GetLongitude() string {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return ""
}

func (m *Location) GetAltitudeMsl() string {
	if m != nil && m.AltitudeMsl != nil {
		return *m.AltitudeMsl
	}
	return ""
}

func (m *Location) GetGroundSpeed() string {
	if m != nil && m.GroundSpeed != nil {
		return *m.GroundSpeed
	}
	return ""
}

func (m *Location) GetHeading() string {
	if m != nil && m.Heading != nil {
		return *m.Heading
	}
	return ""
}

func init() {
	proto.RegisterType((*Location)(nil), "Location")
}

var fileDescriptor0 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xc9, 0x4f, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x03, 0x73, 0x95, 0x72, 0xb8,
	0x38, 0x7c, 0xa0, 0x22, 0x42, 0x02, 0x5c, 0x1c, 0x39, 0x40, 0x56, 0x49, 0x69, 0x4a, 0xaa, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0xa7, 0x90, 0x20, 0x17, 0x67, 0x4e, 0x7e, 0x5e, 0x3a, 0x44, 0x88, 0x09,
	0x2c, 0x24, 0xc2, 0xc5, 0x93, 0x98, 0x03, 0x51, 0x14, 0x9f, 0x5b, 0x9c, 0x23, 0xc1, 0x0c, 0x13,
	0x4d, 0x2f, 0xca, 0x2f, 0xcd, 0x4b, 0x89, 0x2f, 0x2e, 0x48, 0x4d, 0x4d, 0x91, 0x60, 0x01, 0x8b,
	0xf2, 0x73, 0xb1, 0x67, 0xa4, 0x26, 0xa6, 0x64, 0xe6, 0xa5, 0x4b, 0xb0, 0x82, 0x04, 0x00, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x49, 0xd0, 0xff, 0x4c, 0x84, 0x00, 0x00, 0x00,
}
